### ISSUE TITLE
Minor tweaks

### ISSUE THREAD

**Issue by Robadob** [RSE-Sheffield/COMCUDA_mosaic_assignment#2]
Noticed these this year, to be updated before the assignment is re-used.

- [x] Release build config should have `--lineinfo` enabled (makefile already has it).
- [x] The argument `location` in the two `CUDA_CHECK()` macro fns is redundant and should be removed ([here](https://github.com/RSE-Sheffield/COMCUDA_2022/blob/196b3307cfa6579366c1ab786a6da8513bec8876/src/cuda.cuh#L46)).
- [x] Possibly worth adding the two includes `#include <stdlib.h>` and `#include <string.h>` to `openmp.c`. Without `stdlib.h`, `malloc()` is undefined, this produces a compilation warning, and leads to the return value not being a valid pointer (I assume the compiler assumes it returns an int, so it implicitly casts the first 4 bytes of the rval to a pointer).
- [x] Could include a variation of the batch file for running their program through compute sanitizer, to make it easier for students.
- [x] Reset `global_image_average` passed to stage 2 during bench mode (some students are `+=` to it or something).
- [x]  The first OpenMP parallel for has an initialisation cost built in, this leads to diff stage 1 time between bench and none bench mode. (calling `omp_set_num_threads()` does not trigger that init early).
- [x] Add a README to the sample image directory, clarifying that the samples are not exhaustive. Marking will use different images, including larger/smaller/portrait/landscape etc. And that the image loader will automatically crop images to match the tile size on load, so most Jpeg/Png images should be sufficient.
- [x] Coloured pass/fail
- [x] Update makefile so binary is named `Mosaic`
~~- [ ] `cudaPointerGetAttributes()` (See Pete's comment below)~~ (Moved to [separate issue](https://github.com/RSE-Sheffield/COMCUDA_2022/issues/4))
- [x] Add `#include <omp.h>` to `openmp.c`

Ticked changes should be present in the [`coloured_pass_fail`](https://github.com/RSE-Sheffield/COMCUDA_2022/tree/coloured_pass_fail) branch

**Comment by ptheywood** [comment]
It may be worth adding use of `cudaPointerGetAttributes` in the validation methods (assuming cuda is always available) to detect when users pass device pointers to the validation methods, and provide them with a useful error message. 
CUDA 11.0+ this should be relatively simple (if the docs are to be belived), older CUDA's will need some manual error handling in the case of unregistered host pointers (I.e. the expected use case). 

CUDA's that didnt' support UVA on windows might not like this at all either. Shouldn't be an issue though as Windows + UVA has been supported since ~ CUDA 8 IIRC.

[Docs](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__UNIFIED.html#group__CUDART__UNIFIED)
